### ISSUE TITLE
Home page artwork

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-theme#19]
In each products Product Organization section I added 'Village is Family' in to the Home Page collection and removed that tag from 'Free', which was there previously. However it kept Free on the home page and didn't add Village is Family. I then just deleted Free (made it inactive) to see what would happen and it removed from the homepage, but didn't replace it with Village.

**Comment by jonathanwburr** [comment]
We are not currently using the homepage collection, I will delete it. The artwork featured on the homepage is managed in the featured product field on the homepage, https://gyazo.com/70c62e928f4296ae8d6d9298dba64ee0
The plan was to create a carousel in the future but trying to manage where we spend efforts in order to get ready for launch.

**Comment by ZiggyAtl** [comment]
OK thanks Jon
