### ISSUE TITLE
Social media icons

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-theme#8]
@paulstroot  I tried to add the tiktok icon to the footer of the website and also to change the old twitter one to X. Went to Theme - Home Page - Footer - Social media icons - and made sure "Show social media icons" was checked, which it was, and in 'Theme settings' I entered the CoM tiktok account details. But the tiktok icon hasn't appeared and the X logo is still the old twitter one.

**Comment by paulstroot** [comment]
I updated these for you. It should be noted though that because we are using custom icons for our social media links, you can not add additional social media links without developer help. I believe we've accomplished what we set out to do with this task though so you can close it if it's looking okay to you.

**Comment by ZiggyAtl** [comment]
@paulstroot thank you
